version: '3'
services:
  neon-wallet-db:
    container_name: "neon-wallet-db"
    image: slipoh/neon-wallet-db:latest
    environment:
      - MONGOURL=mongodb:27017
      - MONGOPASS=neo
      - MONGOUSER=gas
      - MONGOAPP=test
      - REDISTOGO_URL=redis://redis:6379
      - PYTHONUNBUFFERED=0
      - NET=private
      - PRIVNET_SEEDS=http://neo-privnet:30333,http://neo-privnet:30334,http://neo-privnet:30335,http://neo-privnet:30336
    ports:
      - 5000:5000
    links:
      - mongodb:27017
      - redis:6379
      - neo-privnet:20333
      - neo-privnet:20334
      - neo-privnet:20335
      - neo-privnet:20336
      - neo-privnet:30333
      - neo-privnet:30334
      - neo-privnet:30335
      - neo-privnet:30336
    depends_on:
      - mongodb
      - redis
      - neo-privnet
  neo-privnet:
    image: neo-compiler-privnet-with-gas
    container_name: "neo-compiler-privnet-with-gas"
    ports:
      - 20333:20333
      - 20334:20334
      - 20335:20335
      - 20336:20336
      - 30333:30333
      - 30334:30334
      - 30335:30335
      - 30336:30336
  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - 6379:6379
  mongodb:
    image: tutum/mongodb:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  neo-scan:
    image: slipoh/neo-scan
    container_name: "neo-scan"
    ports:
      - 4000:4000
    links:
      - postgresql:postgres
      - neo-privnet:20333
      - neo-privnet:20334
      - neo-privnet:20335
      - neo-privnet:20336
      - neo-privnet:30333
      - neo-privnet:30334
      - neo-privnet:30335
      - neo-privnet:30336
    depends_on:
      - postgresql
      - neo-privnet
  postgresql:
    image: postgres:10.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
